### ISSUE TITLE
Mysteriously poor performance on macOS

### ISSUE THREAD

**Issue by nielsmh** [OpenTTD/OpenTTD#7644]
## Version of OpenTTD
1.9.0 and later, at least

## Expected result
All operating systems have comparable performance when running on comparable hardware.

## Actual result
Several people are reporting that the macOS version of OpenTTD has unreasonably poor performance, and the framerate window does not reveal any obvious reason.

This bug covers the situation when all of the following occur at the same time:
- Game is running on macOS
- Frame rate on a new game (256x256) with no mods is below 30 fps (typically even below 10 fps)
- Sum of "Game loop", "Drawing" and "Video output" times in the Frame rate window is below 10 ms
- Toggling "Full animation" does not have a significant impact on performance

Reported [on TT-Forums](https://www.tt-forums.net/viewtopic.php?f=31&t=85063) and [this comment](https://github.com/OpenTTD/OpenTTD/issues/7247#issuecomment-505035209) on bug #7247.

Note that this is _not_ related to #7247, as this bug manifests even when there are zero vehicles in game. The poor performance is also caused by something not being measured, since the sum of the game loop, drawing, and video output times do not add up to the time it should to cause the total frame rate.

## Steps to reproduce
Run official OpenTTD builds on a macOS 10.14 system.

**Comment by andythenorth** [comment]
This manifests for me on Mojave (10.14) and did not occur on High Sierra (10.13).

Notably:

* FFWD was insanely fast on 10.13 following OpenTTD improvements in 2018-2019
* FFWD barely works on 10.14
* on a small game (2 AIs,  1500 vehicles  total, 512x256 map), performance is dropping to 16 FPS, and one CPU core is pegged at 100%  by OpenTTD

**Comment by nielsmh** [comment]
Some additional notes:
- The total frame time budget in OpenTTD is 30 ms. The target frame rate is 33.33 fps, which is reached by having on average 30 ms between each frame.
- This means that as long as the total of game loop (time taken simulating the game world), drawing (time producing the graphics for display on screen), and video output (time taken copying the produced graphics to the OS display driver) is less than 30 ms, the frame rate should be roughly 33.33 fps, when not in fast-forward mode.
- Converting frame rate to frame time: _ft_ = 1000 / _fps_
- Converting frame time to frame rate: _fps_ = 1000 / _ft_
- When not in fast-forward mode, the OpenTTD "video driver" component inserts delays between frames to reach an average of 30 ms frame time.
- When fast-forward mode is enabled, these delays are not inserted and instead the game is simulated and drawn as fast as the computer can handle.

Example, taken from times measured on my Windows system running 1.9.2 64 bit:
- Frame rate on the title screen is about 32.96 fps, so the frame time is about 30.33 ms
- The game loop, drawing, and video output times are 0.50 ms, 2.62 ms, 2.50 ms, the sum is 5.62 ms, so if I could enable fast-forward on the title screen, the expected rate would be at least 177.94 fps.
- The actual rate in fast-forward mode can be higher, since a recent change allows multiple game ticks to be simulated between each draw, so the total game loop rate might end up closer to 2000 fps.

The frame rate window (and fps console command) also display a line for Sound mixing, this is generally not relevant, since sound mixing is run in a separate thread. It should never affect total frame rate. (It could get relevant if someone reported crackling/popping sound.)

**Comment by wousser** [comment]
As requested:
```
ProductName:	Mac OS X
ProductVersion:	10.14.5
BuildVersion:	18F132
```

**1.8.0**
No issues
Both with Full Animation Enabled or Disabled the game runs smoothly. (No fps command in 1.8.0)

**1.9.0**
Full animation Enabled:
```
Game loop rate: 14.94fps (expected 33.33fps)
Drawing rate: 14.96fps (expected 33.33fps)
Video output rate: 35.99fps (expected 60.00fps)
```

Full animation Disabled:
```
Game loop rate: 29.18fps (expected 33.33fps)
Drawing rate: 29.28fps (expected 33.33fps)
Video output rate: 155.36fps (expected 60.00fps)
```

**1.9.2**
Full animation Enabled:
```
Game loop rate: 14.70fps (expected 33.33fps)
Drawing rate: 14.66fps (expected 33.33fps)
Video output rate: 54.38fps (expected 60.00fps)
```

Full animation Disabled:
```
Game loop rate: 30.87fps (expected 33.33fps)
Drawing rate: 30.88fps (expected 33.33fps)
Video output rate: 195.84fps (expected 60.00fps)
```

I'd like to add that this only occurs when playing full-screen or full window. If I reduce the window size to 1/4 of the screen, the FPS increases to ~30.

**Comment by drebroff** [comment]
Confirm 
ProductName:	Mac OS X
ProductVersion:	10.14.5

MacBook Pro 15 2017

**Comment by AbeWJS** [comment]
OpenTTD is causing color space / pixel format conversion in the background. Likely due to mismatch of backing surface format chosen by OpenTTD and native surface format of the display/OS.

The slowdown scales with OpenTTD resolution and Mac machine's high resolution exacerbates the problem. This format/color space conversion happens on OpenTTDs main thread after a call to CGContextDrawImageWithOptions.

I don't have time to look at this in the source, but that is where the problem comes from. Perhaps these pointers are enough information?

**Comment by andythenorth** [comment]
I don't have any skills in Mac debugging, but I used Apple instructions to set up an Instruments run, long paste of results here: https://paste.openttdcoop.org/pef0g4kgn/mnd7ty/raw

TL;DR
-  98.5% of time is spent in OTTD_QuartzView drawRect
- digging down, 29% of the time is spent in RGBAf16_sample_RGBAf_inner

A cursory google search turns up a few other people with similar issue, nothing conclusive
- https://forums.developer.apple.com/thread/79474
- https://stackoverflow.com/questions/55803357/improve-cgcontextdrawimage-performance

Apple developer guide is here: https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CocoaViewsGuide/Optimizing/Optimizing.html#//apple_ref/doc/uid/TP40002978-CH11-SW4

My results are for macOS 10.14, on a 2.7Ghz i7

**Comment by nielsmh** [comment]
So if the rendering was changed to use explicit GPU acceleration instead of blitting 2D surfaces, it might resolve the issue? Since the GPU could receive texture data in our native pixel format, and a shader could convert it as necessary.

**Comment by SoothedTau** [comment]
@nielsmh 

You could indeed switch to a MTKView (or other Metal view) and use Metal to do the transfer while having a shader convert the image to the final format. This would work just fine.

Though I don't think you have to do it via Metal as it should be possible to set things up correctly without requiring Metal. This new behaviour likely has to do with changes to Layer Backed Views introduced in 10.14 SDK, I'll see if I can find out what exactly introduces the observed behavior.

In the end it's just a choice but I could imagine not wanting to introduce a new dependency if it's not necessary.

**Comment by nielsmh** [comment]
I think we definitely want to support macOS versions as far back as reasonably possible, at least not having hard dependencies on newer features.

**Comment by faeton** [comment]
Just wanted to confirm here that the issue is important and in place. Tested on 10.14 and 10.13 both showing bad results, low fps, mouse pointer lags.

**Comment by SoothedTau** [comment]
Trying to track this down but having issues getting a build working. Built master repo without any compression libs, build succeeded, but when executing I immediately encounter an error in libdyld: stack_not_16_byte_aligned. 

Probably missing some steps getting the build running. Can dig further if someone can help me out here :)

**Comment by DIYglenn** [comment]
Anything I can test? 
If anything I can at least confirm the issue on a 5K iMac 2019 - 1.9.2 is unplayable, 1.8.0 seems to work as normal (but slower with 1440p resolution, which might actually be twice the resolution due to Retina)

**Comment by DIYglenn** [comment]
From [my thread on Reddit](https://www.reddit.com/r/openttd/comments/cuasm7/imac_27_2019_horrible_performance/):

> I have a 13” MBP w/ TouchBar. When I play in the native resolution, the game is laggy as all hell... but when I connect it to an external monitor (1080p), it’s fine. When I switch to Windows 10 via Bootcamp also with 1080p resolution, it’s perfectly fine.
> I don’t have a solution to the issue, but I hope this might shed some light.
> I hope you’ll share the solution when you solve it! Good luck! 

So is the issue only Retina related?
Anyone with non-retina Mac's that experience problems?
I have a Mac Pro with Mojave and a 1440p monitor (non-retina) where I can fire it up and test.

**Comment by nielsmh** [comment]
I think it's worth testing with both 32bpp and 8bpp blitters. Probably worth testing with driver debug enabled (level 1) to be sure the expected blitter is selected.

I'm not entirely sure about how to run with a commandline on macOS, it's too many years since, but try this from a terminal:
`OpenTTD.app/Contents/MacOS/openttd -b 8bpp -d driver=1`

**Comment by DIYglenn** [comment]
> I think it's worth testing with both 32bpp and 8bpp blitters. Probably worth testing with driver debug enabled (level 1) to be sure the expected blitter is selected.
> 
> I'm not entirely sure about how to run with a commandline on macOS, it's too many years since, but try this from a terminal:
> `OpenTTD.app/Contents/MacOS/openttd -b 8bpp -d driver=1`

Tried your exact command. Got a "pixelated" error. Interesting.
<img width="532" alt="Skjermbilde 2019-08-27 kl  13 14 47" src="https://user-images.githubusercontent.com/10504432/63767013-ba89fe00-c8cc-11e9-981f-b2fa17338eb4.png">

This did however work:
`openttd -b 8bpp-optimized -d driver=1`

Not sure what 8bpp vs 8bpp-optimized is? 

Although I can confirm that 
`/Applications/OpenTTD/OpenTTD.app/Contents/MacOS/openttd -b 8bpp-optimized -d driver=1`
Does indeed seem to make 1.9.2 run as good as 1.8.0. Mouse is a bit laggy on the menu (both in 1.8.0 and 1.9.2). Moving around the map isn't as smooth as on my Windows PC.

**I also tested with 32bpp-optimized and this is really interesting!!**
`/Applications/OpenTTD/OpenTTD.app/Contents/MacOS/openttd -b 32bpp-optimized -d driver=1`
I'm using A-base, and it seems to run really smooth! The mouse pointer seems to be "perfect", no lag. Not sure about moving around the map, seems like it's as smooth as it can be. 
- I'll have to test with a better mouse than my Magic Trackpad 2.



Explaination?

**Comment by DIYglenn** [comment]
Tests:
**1.9.2 normal**. Mouse is laggy, game is laggy, moving around gives noticeable stutter:
![1 9 2](https://user-images.githubusercontent.com/10504432/63768505-a6e09680-c8d0-11e9-8fb2-9a2ff41b0b31.png)

**1.9.2 with blitter 32bpp-optimized**. Mouse is butter smooth in menus and in-game, moving around seems to give a slight stutter, could be better? I feel it's smoother on my PC:
![1 9 2-32bpp](https://user-images.githubusercontent.com/10504432/63768632-08086a00-c8d1-11e9-96ee-72be25e60af6.png)

**1.9.2 with blitter 8bpp-optimized**. Mouse is stuttering a bit (maybe) but much better, moving around seems like with 32bpp-optimized - fairly smooth, but seems to have a slight stutter. 
![1 9 2-8bpp](https://user-images.githubusercontent.com/10504432/63768718-456cf780-c8d1-11e9-9810-27ba1619c4fb.png)

All in all it is 30FPS vs 8FPS and the game feels playable. But it feels just as "stuttery" in 1.8.0 as well. Shouldn't it be possible to get a lot more than 30FPS?

Changing resolution between 5120x2880 and 2560x1440 makes absolutely no difference, so it seems like it's running at 1440p? Decreasing resolution with 1.9.2 "normal" increases FPS, but never much higher than ~30FPS.

Changing resolution with 1.9.2 8bpp-optimized or 32bpp-optimized makes no difference. It's steady at 30-35FPS no matter the resolution, even down to a tiny window. (although 1440p and 2880p seems to be the same resolution, retina-thing?)

Output when running the command:
```
dbg: [driver] Successfully loaded blitter '32bpp-optimized'
dbg: [driver] Could not change to foreground application. Error -50
dbg: [driver] Successfully probed video driver 'cocoa'
dbg: [driver] Successfully probed sound driver 'cocoa'
dbg: [driver] Successfully probed music driver 'cocoa'
```

**Comment by nielsmh** [comment]
I'm interested in what the default blitter is when you don't override it on the commandline.

**Comment by DIYglenn** [comment]
> I'm interested in what the default blitter is when you don't override it on the commandline.

I would guess 32bpp-anim. At least that gave me the same performance as before. 
Any way I can test?
Also - what FPS should I expect?

**Comment by nielsmh** [comment]
If you run `OpenTTD.app/Contents/MacOS/openttd -d driver=1` (i.e. leave out the blitter argument but keep the debug argument) it should write to the terminal which blitter it selects.

The expected framerate (when simulation is not too heavy for the CPU) is 33.33 fps, but anything between 32 and 34 is acceptable.

**Comment by SoothedTau** [comment]
> From [my thread on Reddit](https://www.reddit.com/r/openttd/comments/cuasm7/imac_27_2019_horrible_performance/):
> 
> > I have a 13” MBP w/ TouchBar. When I play in the native resolution, the game is laggy as all hell... but when I connect it to an external monitor (1080p), it’s fine. When I switch to Windows 10 via Bootcamp also with 1080p resolution, it’s perfectly fine.
> > I don’t have a solution to the issue, but I hope this might shed some light.
> > I hope you’ll share the solution when you solve it! Good luck!
> 
> So is the issue only Retina related?
> Anyone with non-retina Mac's that experience problems?
> I have a Mac Pro with Mojave and a 1440p monitor (non-retina) where I can fire it up and test.

As I mentioned earlier; this is a colourspace/format problem. The OS has detected that the pixels it is being given by OpenTTD are not in the exact colourspace/format that the monitor is accepting at that time. An external monitor likely has a different, in this case more compatible, colourspace than the built-in screen, which is why the problem doesn't exist.

I've checked the colourspace code and it seems fine though. Obviously selecting a different blitter changes how the OS handles things, which is great info. It would be useful to know the exact difference between the blitters, in particular what kind of surface they request from the OS and what colourspace they choose for it.

**Comment by DIYglenn** [comment]
> If you run `OpenTTD.app/Contents/MacOS/openttd -d driver=1` (i.e. leave out the blitter argument but keep the debug argument) it should write to the terminal which blitter it selects.
> 
> The expected framerate (when simulation is not too heavy for the CPU) is 33.33 fps, but anything between 32 and 34 is acceptable.

Oh OK. I read something about expecting 800 frames in the thread that led me here, so that put me off.

**Comment by DIYglenn** [comment]
@SoothedTau Ok, sorry. If there’s anything I can test, let me know.

**Comment by AbeWJS** [comment]
> @SoothedTau Ok, sorry. If there’s anything I can test, let me know.

No need to apologise! All data is good data, your comment cemented what I already thought. I've seen this behavior on macOS before where external screens don't have the same issues simply due to being a different type of screen. (Retina vs Non-retina for example, but HDR/Non-HDR as well).

I'm still stuck on not being able to run the game after having built it, I wanted to debug and test some minor changes but as I can't produce working executables it's a little hard :).

**Comment by nielsmh** [comment]
> 
> 
> > If you run `OpenTTD.app/Contents/MacOS/openttd -d driver=1` (i.e. leave out the blitter argument but keep the debug argument) it should write to the terminal which blitter it selects.
> > The expected framerate (when simulation is not too heavy for the CPU) is 33.33 fps, but anything between 32 and 34 is acceptable.
> 
> Oh OK. I read something about expecting 800 frames in the thread that led me here, so that put me off.

That's in fast-forward. The game needs to run at 33.33 fps in normal mode to run at full speed, but should generally be capable of running much faster in fast-forward mode, depending on CPU. Definitely do test with a new game (no vehicles, 256x256 map) how fast it can run.

**Comment by DIYglenn** [comment]
Ah. Makes sense. I’ll do some more testing in my systems. 
So where’s the problem with building it? Is there anything I can do to test?

**Comment by AbeWJS** [comment]
Had some time to look at this last evening and the issue is, as expected, due to a mismatch in colourspaces:

OpenTTD queries the system for the colourspace of the monitor. On many monitors (including external ones!) this returns a pretty standard sRGB colourspace which works just fine with how OpenTTD handles colours internally. What happens in this case, and which causes problems for OpenTTD, is that the main display of iMacs and MacBooks actually returns a P3 colourspace as its best fit because these displays are capable of more than what sRGB supports (they are pretty good displays!). Now OpenTTD tries to use P3 even though it really shouldn't as its outputting in the sRGB colourspace which means the pixel data is incompatible and thus won't look right. Additionally, the system introduces a conversion step from an internal image to the image the OS will use to show the window, this step is very costly as the P3 colourspace requires much more data per pixel than the usual sRGB space and the pixel formats involved in P3 are far more complex to convert between.

All relevant code for this problem is in wnd_quartz.mm. Here is a breakdown of it: The NSWindow that OpenTTD uses (created on line 287, WindowQuartzSubdriver::SetVideoMode) is in the P3 colourspace by default when running on the main display of a Mac. The CGContext that is used (created on line 605, WindowQuartzSubdriver::WindowResized) to store OpenTTD's drawing results internally is created with a colourspace from QZ_GetCorrectColorSpace (line 109) which returns whatever CGDisplayCopyColorSpace (line 116) returns which is in the case of running on the main display of a Mac; also P3. These two combined result in very slow calls to CGContextDrawImage (line 191 and 212, (void)drawRect:(NSRect)invalidRect) which is what drags down the performance of the game.

To get around the issue I made changes to 2 lines. Objective is to prevent running with a P3 colourspace. macOS is pretty smart and will make sure everything looks right even when mixing colourspaces as long as we tell it in what space the pixels we give it are. With that in mind I changed line 116 to always return a standard sRGB colourspace:

`colorSpace = CGColorSpaceCreateWithName(kCGColorSpaceSRGB);`

And added a new line after line 291 that sets the colourspace of the window to match the one we use internally: 

`[this->window setColorSpace:[[[NSColorSpace alloc]initWithCGColorSpace:QZ_GetCorrectColorSpace()] autorelease]];
`
With these two changes I get much improved performance and everything looks right. I can't make the actual change in the code for reasons so someone else will have to do that but it should be pretty straightforward. I should add that this fix did not go through extensive testing and there are edge-cases I'm likely unaware of but I think it should work for most if not all cases. Probably important to test on an external monitor too to see if that's still alright.

P.S.: If someone is willing to; is anyone else seeing issues with compiling the release version on macOS? I was seeing misaligned stack errors and had to enable debug mode to compile a working binary. Wondering if any of you sees the same error? I was compiling with Xcode 11 beta on Catalina.

**Comment by SoothedTau** [comment]
Had some time to look at this last evening and the issue is, as expected, due to a mismatch in colourspaces:

OpenTTD queries the system for the colourspace of the monitor. On many monitors (including external ones!) this returns a pretty standard sRGB colourspace which works just fine with how OpenTTD handles colours internally. What happens in this case, and which causes problems for OpenTTD, is that the main display of iMacs and MacBooks actually returns a P3 colourspace as its best fit because these displays are capable of more than what sRGB supports (they are pretty good displays!). Now OpenTTD tries to use P3 even though it really shouldn't as its outputting in the sRGB colourspace which means the pixel data is incompatible and thus won't look right. Additionally, the system introduces a conversion step from an internal image to the image the OS will use to show the window, this step is very costly as the P3 colourspace requires much more data per pixel than the usual sRGB space and the pixel formats involved in P3 are far more complex to convert between.

All relevant code for this problem is in wnd_quartz.mm. Here is a breakdown of it: The NSWindow that OpenTTD uses (created on line 287, WindowQuartzSubdriver::SetVideoMode) is in the P3 colourspace by default when running on the main display of a Mac. The CGContext that is used (created on line 605, WindowQuartzSubdriver::WindowResized) to store OpenTTD's drawing results internally is created with a colourspace from QZ_GetCorrectColorSpace (line 109) which returns whatever CGDisplayCopyColorSpace (line 116) returns which is in the case of running on the main display of a Mac; also P3. These two combined result in very slow calls to CGContextDrawImage (line 191 and 212, (void)drawRect:(NSRect)invalidRect) which is what drags down the performance of the game.

To get around the issue I made changes to 2 lines. Objective is to prevent running with a P3 colourspace. macOS is pretty smart and will make sure everything looks right even when mixing colourspaces as long as we tell it in what space the pixels we give it are. With that in mind I changed line 116 to always return a standard sRGB colourspace:

`colorSpace = CGColorSpaceCreateWithName(kCGColorSpaceSRGB);`

And added a new line after line 291 that sets the colourspace of the window to match the one we use internally: 

`[this->window setColorSpace:[[[NSColorSpace alloc]initWithCGColorSpace:QZ_GetCorrectColorSpace()] autorelease]];`

With these two changes I get much improved performance and everything looks right. I can't make the actual change in the code for reasons so someone else will have to do that but it should be pretty straightforward. I should add that this fix did not go through extensive testing and there are edge-cases I'm likely unaware of but I think it should work for most if not all cases. Probably important to test on an external monitor too to see if that's still alright.

P.S.: If someone is willing to; is anyone else seeing issues with compiling the release version on macOS? I was seeing misaligned stack errors and had to enable debug mode to compile a working binary. Wondering if any of you sees the same error? I was compiling with Xcode 11 beta on Catalina.

**Comment by SoothedTau** [comment]
I'd like to add that in a debug version of that game I can still see 50% of the time being spent copying pixels in the functions mentioned above. I don't know what the situation was before this issue was present, but if it wasn't 50% before it should be investigated further as you are likely still on a (much) slower path than before.

**Comment by andythenorth** [comment]
I can repro this diagnosis, checking fps with full animation on
- Display p3: ~10fps
- sRGB: ~35fps

Using a patch containing the changes from @SoothedTau above:
- Display p3: ~34fps
- sRGB: ~34fps

So the patch appears to achieve the expected result. 👍  Note that the minor difference of 35fps (unpatched) vs 34fps (patched) is likely just local performance variation.

I am only able to test on the native screen on my macbook pro.  That's 13" Retina P3.  I don't have an external screen to test with.

In previous comment I provided results of an Instruments run, with 98% of time spent in OTTD_QuartzView drawRect https://github.com/OpenTTD/OpenTTD/issues/7644#issuecomment-521895427

Out of curiosity I did another Instruments run for the patch in #7721, which shows 77% of time is now spent in OTTD_QuartzView drawRect 
https://paste.openttdcoop.org/pm3vmrdyo/ix8ac9/raw

However I don't know enough about macOS debugging to call that a significant result.  

Notable though that 29% of time was previously spent in RGBAf16_sample_RGBAf_inner, which no longer appears in the call stack with the #7721 patch.

**Comment by andythenorth** [comment]
One note is that that the colorspace change does result in visible changes to the game appearance (see screenshot).  

To my eye, the 7644 version is more yellow and washed out, and subjectively I prefer the version labelled 'master', but this might just be due to familiarity with the existing color handling.

FTR, @michicc asked what happens with only the second line from the patch, and no colorspace change: afaict, the performance benefit is the same in that case.

<img width="382" alt="7644_colours" src="https://user-images.githubusercontent.com/1780327/64292484-6a610a80-cf62-11e9-8290-45328aea397e.png">

**Comment by SoothedTau** [comment]
Less changes is usually better! Let me try and repro the results you are seeing, I thought I tried the same thing but I may have messed it up.

**Comment by SoothedTau** [comment]
It seems that on Catalina both lines are required to see the speed-up. If I revert the change in QZ_GetCorrectColorSpace I get the old performance degradation back. It may be worth trying RGB instead or SRGB or linear. Not sure what colourspace OpenTTD outputs usually...

**Comment by nielsmh** [comment]
OTTD doesn't have a defined colourspace as such, since the graphics is originally just based around an 8bpp SVGA palette. I don't think VGA or SVGA ever defined colour reproduction strictly. On the other hand isn't that exactly what sRGB set out to standardise?

**Comment by Eddi-z** [comment]
might this depend on whether you use an 8bpp or 32bpp baseset/newgrfs?

**Comment by SoothedTau** [comment]
> OTTD doesn't have a defined colourspace as such, since the graphics is originally just based around an 8bpp SVGA palette. I don't think VGA or SVGA ever defined colour reproduction strictly. On the other hand isn't that exactly what sRGB set out to standardise?

I've tried a bunch of colorspaces to see what the results are and there are only 2 real options: kCGColorSpaceGenericRGB and kCGColorSpaceSRGB. The rest is either obviously wrong or induces the same slowdown as we saw before. Unfortunately kCGColorSpaceGenericRGB is deprecated, you are actually advised to use kCGColorSpaceSRGB instead even though results are not exactly the same (see [here](https://developer.apple.com/documentation/coregraphics/kcgcolorspacegenericrgb?language=objc)).

Here are two full sized screenshots labeled with their color spaces. It looks like these two match the ones Andy posted. Would lead me to believe kCGColorSpaceGenericRGB was used in 'master'. Personally, I think kCGColorSpaceSRGB produces the right results, the browns in the forest look too bright to me with kCGColorSpaceGenericRGB for example. Anyway, it's up to you guys.

<img width="1451" alt="Screenshot 2019-09-05 at 08 57 08" src="https://user-images.githubusercontent.com/54182484/64359196-b345ad00-cfbc-11e9-93d3-46583b94612b.png">

<img width="1451" alt="Screenshot 2019-09-05 at 08 54 24" src="https://user-images.githubusercontent.com/54182484/64359357-015ab080-cfbd-11e9-836a-104be13fb619.png">

**Comment by glx22** [comment]
I'm not a macOS user but kCGColorSpaceSRGB image looks similar to what I see on windows and kCGColorSpaceGenericRGB is really too bright.

**Comment by nielsmh** [comment]
Confirm SRGB looks correct, GenericRGB is wrong gamma.

**Comment by andythenorth** [comment]
Another +1 for kCGColorSpaceSRGB

EDIT: I'm -1 to this currently, what I see locally with kCGColorSpaceSRGB is very different to master - see https://github.com/OpenTTD/OpenTTD/issues/7644#issuecomment-528875224

**Comment by DIYglenn** [comment]
> > > If you run `OpenTTD.app/Contents/MacOS/openttd -d driver=1` (i.e. leave out the blitter argument but keep the debug argument) it should write to the terminal which blitter it selects.
> > > The expected framerate (when simulation is not too heavy for the CPU) is 33.33 fps, but anything between 32 and 34 is acceptable.
> > 
> > 
> > Oh OK. I read something about expecting 800 frames in the thread that led me here, so that put me off.
> 
> That's in fast-forward. The game needs to run at 33.33 fps in normal mode to run at full speed, but should generally be capable of running much faster in fast-forward mode, depending on CPU. Definitely do test with a new game (no vehicles, 256x256 map) how fast it can run.

Tested with 256x256 and normal + fast forward. These are average-ish results as it's jumping up and down by a lot when autosaving:

**1.9.2 with no changes to config:**
_Normal speed_
- Simulation rate 18 FPS
- Graphics frame rate 18.5 FPS
- Game speed factor 0.5x

_Fast forward_
- Simulation rate 400 FPS
- Graphics frame rate 140 FPS
- Game speed factor 12x

**1.9.2 with "_32bpp-optimized_":**
_Normal speed_
- Simulation rate 34 FPS
- Graphics frame rate 34 FPS
- Game speed factor 1.0x

_Fast forward_
- Simulation rate 4500 FPS
- Graphics frame rate 200 FPS
- Game speed factor 135x

Note - Fast forward jumps from everything between 3000 and 8000 due to autosave it seems.

**Comment by DIYglenn** [comment]
@SoothedTau 
kCGColorSpaceSRGB definitely looks much better than kCGColorSpaceGenericRGB. Generic is way too bright.

Btw - Are you using original graphics? Because although brightness etc. seems to match, your tiles are different. 
If so - could you post some OpenGFX screens as well? Easier for me to compare with my Mac.

**Comment by andythenorth** [comment]
@SoothedTau what colorspace is your display running in?  Your sRGB screenshot is very different to what I get locally.  My display is running in native p3, and with the kCGColorSpaceSRGB patch, OpenTTD is very muddy, and has a magenta cast.  Colour problems :)

<img width="509" alt="kCGColorSpaceSRGB" src="https://user-images.githubusercontent.com/1780327/64435381-47e20500-d0ba-11e9-8d1c-e403be9c0664.png">

**Comment by glx22** [comment]
@andythenorth when I put my windows window next to your image, both seem a little different, but patched is definitely closer to windows

**Comment by AbeWJS** [comment]
> @SoothedTau
> kCGColorSpaceSRGB definitely looks much better than kCGColorSpaceGenericRGB. Generic is way too bright.
> 
> Btw - Are you using original graphics? Because although brightness etc. seems to match, your tiles are different.
> If so - could you post some OpenGFX screens as well? Easier for me to compare with my Mac.

I am indeed running original graphics, it's the only ones I'm familiar with. But I can produce some screenshots later on with the new graphics. 

> @SoothedTau what colorspace is your display running in? Your sRGB screenshot is very different to what I get locally. My display is running in native p3, and with the kCGColorSpaceSRGB patch, OpenTTD is very muddy, and has a magenta cast. Colour problems :)
> 
> <img alt="kCGColorSpaceSRGB" width="509" src="https://user-images.githubusercontent.com/1780327/64435381-47e20500-d0ba-11e9-8d1c-e403be9c0664.png">

That's a very odd issue, totally unexpected! Can you confirm what that exact building normally looks like without the patch? I haven't seen any unexpected colors myself while using original graphics, could you try the original graphics too and see if you find similar issues there?

**Comment by SoothedTau** [comment]
> @SoothedTau
> kCGColorSpaceSRGB definitely looks much better than kCGColorSpaceGenericRGB. Generic is way too bright.
> 
> Btw - Are you using original graphics? Because although brightness etc. seems to match, your tiles are different.
> If so - could you post some OpenGFX screens as well? Easier for me to compare with my Mac.

I am indeed running original graphics, it's the only ones I'm familiar with. But I can produce some screenshots later on with the new graphics.



> @SoothedTau what colorspace is your display running in? Your sRGB screenshot is very different to what I get locally. My display is running in native p3, and with the kCGColorSpaceSRGB patch, OpenTTD is very muddy, and has a magenta cast. Colour problems :)
> 

That's a very odd issue, totally unexpected! Can you confirm what that exact building normally looks like without the patch? I haven't seen any unexpected colors myself while using original graphics, could you try the original graphics too and see if you find similar issues there?

**Comment by andythenorth** [comment]
Meanwhile I checked kCGColorSpaceGenericRGB, and agree that it is worse than kCGColorSpaceSRGB

Left is kCGColorSpaceGenericRGB, right is 1.9.2
<img width="392" alt="kCGColorSpaceGenericRGB" src="https://user-images.githubusercontent.com/1780327/64474908-2d1f9700-d173-11e9-8e39-f7daa8162f66.png">

**Comment by andythenorth** [comment]
I get much better colour using kCGColorSpaceDisplayP3, but I assume that's not going to work on non-P3 displays?  **Also** I don't get the speed benefit, so it's likely moot.

Left is kCGColorSpaceGenericRGB, right is 1.9.2
<img width="335" alt="kCGColorSpaceDisplayP3" src="https://user-images.githubusercontent.com/1780327/64474941-9ef7e080-d173-11e9-8a56-cdbec99403d0.png">

**Comment by nielsmh** [comment]
It looks like there is also a way to get a device-dependent RGB colorspace, and that one actually does get used as a fallback if getting a more specific one fails. The device-dependent colorspace is specified as doing no conversions at all, the pixels you supply are those delivered to the display, basically, so it should be the best performing I think.

However, it seems @andythenorth was getting some strange crashes (even taking down his entire machine) trying to use that. Does anyone else dare try that? `CGColorSpaceCreateDeviceRGB()`.

**Comment by Honza1987** [comment]
Hi still doesn't work - so I downgraded to 1.8.0 there it works properly - 1.9.0 and higher still too slow to play conveniently .. :-/

**Comment by nielsmh** [comment]
@Honza1987 Are you testing with the 1.9.3-RC1 version available from https://www.openttd.org/downloads/openttd-releases/testing.html ? That's the version that has the (attempted) fix applied.

**Comment by Honza1987** [comment]
Oh no sorry will try it right now thx...

**Comment by Honza1987** [comment]
Hi,

so this one is even worse than 1.9.2. - check the screen I attached - monitor activity shows it takes a lot of CPU, if I understand well :-)

Jan

**Comment by nielsmh** [comment]
Sorry the attached screenshot didn't arrive in Github, you'll have to visit the issue webpage to post that I think.

**Comment by SoothedTau** [comment]
> Hi, so this one is even worse than 1.9.2. - check the screen I attached - monitor activity shows it takes a lot of CPU, if I understand well :-) Jan
> […](#)

What hardware are you running on? OS version? 

Also, it's worse how? There is expected to be a lot of CPU usage even with the fix though. I would expect it to be better though, so the fact that its not is surprising.

**Comment by bedrich-schindler** [comment]
I have the same problem on macOS Mojave 10.14.6 on my MacBook Pro 2017 15". When I use external monitor, it works fine. But if built-in MacBook display is used, it is lagging so much.

**Comment by Honza1987** [comment]
Here I took printscreen of monitor activity when playing 1.9.3. - if its helpful
<img width="912" alt="Snímek obrazovky 2019-09-12 v 16 48 04" src="https://user-images.githubusercontent.com/55239273/64822774-0d92cf00-d5b6-11e9-90d4-010cc343406e.png">

**Comment by Cin316** [comment]
FYI, this is the performance I see on 1.8.0 with a simple world.  It uses a good amount of processing power, but it doesn't usually hit 100%.

![image](https://user-images.githubusercontent.com/1988780/64829373-107fc680-d59a-11e9-93ee-f4ea16dc1ae7.png)

**Comment by andythenorth** [comment]
TL;DR: there are multiple Mac performance issues, this patch is only intended to address one.

I can see the significantly increased CPU use in master compared to 1.8, but I haven't bisected to find the rev that introduced it yet.  In master, OpenTTD will peg at or near to 100% of the CPU most of the time.  It may or may not also be connected to upgraded macOS version.

Co-incidental (maybe related, maybe not ) is that Mac FFWD performance got a **huge** fix sometime around 1.8.  FFWD in master then regressed to be highly inconsistent (anywhere from 1x to 1000x).  That hasn't been investigated enough to find a cause yet.  

I also made a video of demonstrating an odd Mac performance issue where FPS lags badly, then FPS is restored to expected value by opening a news message window.  That has not had further investigation afaik.

The patch in this PR for the colorspace does not, as far as I can tell in testing, affect the CPU performance negatively or positively.  What it _does_ do, at least for some of us, is restore the FPS when 'Full Animation' is enabled, which has been broken for years on Mac.  

My testing is on the native retina screen on a 13" Macbook Pro, I don't have an external screen to test with.

**Comment by michicc** [comment]
@Honza1987 If you can compile, you could try the alternative patch from PR #7741. The PR is made for master, but should apply to 1.9.3 branch as well.

**Comment by Honza1987** [comment]
Where can I download that patch to try? I have already tried 1.9.3. and as I wrote it was even worse :/

Jan Peša

jan.pesa@me.con
+420 728 416 888

Odesláno z iPhonu

14. 9. 2019 v 16:38, Michael Lutz <notifications@github.com>:

**Comment by Honza1987** [comment]
Hi,

topic was closed, I don’t just get the point if the problem is solved or not :-D ??

Thank you,

Jan

**Comment by LordAro** [comment]
An additional fix was added into 1.9.3 (on top of the changes in 1.9.3-RC1), which we believe improve things further. As such, we (currently) consider the issue to be solved

**Comment by Honza1987** [comment]
OK I will try 1.9.3.-RC1 and let you know thx.

**Comment by andythenorth** [comment]
I put an earlier comment, but the ticket is quite busy eh? :) 

https://github.com/OpenTTD/OpenTTD/issues/7644#issuecomment-531111316

TL:DR; the color space patches only solve one limited performance issue with full-animation.  For me.  Others may get different results.  There are other performance issues which may or may not be solveable.

**Comment by Honza1987** [comment]
as a normal user I don’t get it :-D so I will try later on if it works otherwise can’t help :-D sorry for spamming thread :-)

**Comment by hgmich** [comment]
I've got pretty horrendus performance on a 2016 MBP pro on 1.9.3 running macOS 10.15, even though this is fixed (perhaps actually a different issue?). This machine was fine running 1.8.0 on 10.14 - unfortunately I can't tell which caused the issue as I upgraded to 1.9.3 in response to 1.8.0 being 32-bit.

<img width="304" alt="Screenshot 2019-11-06 at 23 51 23" src="https://user-images.githubusercontent.com/706183/68347936-67180580-00f0-11ea-9bd8-e986f8f60e6a.png">
As can be seen, performance very bad, yet not even 2ms of work is being done per frame. During this time the game runs at about 80-90% CPU, across 2 cores for about 40-50% load each. There's no other significant load on system CPU or GPU resources and there's plenty of free memory.

**Comment by andythenorth** [comment]
That mirrors my results with 1.9.3 (or current master) on macOS 10.14

* 14-16fps
* low current and average values for all the measured timings
* system CPU and other resources highly available

**I only get this 14-16fps behaviour intermittently.**  

It's unrelated to map size, or number of vehicles and stations, it can occurs with just one or two vehicle, or with a complex game.  It occurs with full animation on or off.

When this behaviour isn't present, the game runs at 34fps for me on a bare map, and gradually declines to 21-22fps, in line with the complexity of the game, number of vehicles etc.

This will sound odd, but try opening a recent news window (click the news bar at the bottom of the screen)....

....when this odd, no-obvious-cause, 14-16fps behaviour occurs for me, it resolves immediately as the news window scrolls open.  I haven't made a video to prove it yet though 😄 

Macbook Pro 2019, 2.8Ghz

**Comment by hgmich** [comment]
I did see mention of this quirk, but on my machine opening the recent news window didn’t seem to fix it. Additionally, this isn’t intermittent - it happens every time I load the game, on both the menu and ingame.

**Comment by andythenorth** [comment]
I made a very inconclusive video on current self-compiled master.  It shows the variability of fps with
* full animation on / off
* highly variable ffwd behaviour

https://dev.openttdcoop.org/attachments/download/9528/7644-mac-performance.mov

Doesn't offer any clues.  I tried autosave on / off to see if that related to the ffwd problem: it appears to be unrelated.

For comparison I made a video of 1.9.1: https://dev.openttdcoop.org/attachments/download/9529/7644-mac-performance-1-9-1.mov
* full animation performance on normal game speed is worse, as expected, compared to master 
* FFWD performance is orders of magnitude better in for both full-animation on and off

Finally I made a comparison with 1.9.3:
https://dev.openttdcoop.org/attachments/download/9530/7644-mac-performance-1-9-3.mov
* full animation performance is about same as 1.9.1
* FFWD performance is much faster than self-compiled master and much worse than 1.9.1

Still no single obvious conclusion.

I also found the video I made of lolz behaviour with news messages.  That predates the colourspace fix in this PR (by one month).  It was always intermittent, but I haven't been able to trigger it recently, doesn't mean it's gone, but eh.  It's worth watching as it's so bizarre. https://dev.openttdcoop.org/attachments/download/9489/mac_fps.mov

**Comment by Honza1987** [comment]
Hi there,

still same problem even in 1.10.0 I made video of that game and it is still so slow … there is no even different between fast and normal play… check it below..

Jan

https://nextcloud.epartners.cz/index.php/s/JEEiMARrWq38xSZ <https://nextcloud.epartners.cz/index.php/s/JEEiMARrWq38xSZ>

**Comment by andythenorth** [comment]
> Hi there, still same problem even in 1.10.0 I made video of that game and it is still so slow … there is no even different between fast and normal play

Try it with 'full animation' off?  Probably still slower than 1.8.0, but worth testing.

**Comment by andythenorth** [comment]
This needs one or both of 

- additional instrumentation in-game to see if there are any unexpectedly long timings
- reports created using Apple's Instrument tool https://help.apple.com/instruments/mac/current/#/dev7b09c84f5

**Comment by nielsmh** [comment]
I'll see if I can define some more measurement points video drivers can report on, some time soon.

**Comment by hgmich** [comment]
I did some cursory timings and the graph on my machine looks to indicate there's a massive amount of copying and image format conversion in the `drawRect` routine when Full Animation is on. Timings were taken with Nightly 2019-11-03 build so that debug symbols make these easier to read.

Like the previous run, there's a big trough in CPU time when Full Animation is off:
![image](https://user-images.githubusercontent.com/706183/68587885-1271e300-0480-11ea-981c-8f866506057a.png)


With full animation off, I'm able to get ~33fps as expected. The call graph for a 7s window with this off looks like this:

```
55.00 ms    9.4%	0 s	 	  -[OTTD_QuartzView drawRect:]
39.00 ms    6.7%	0 s	 	   CGContextDrawImageWithOptions
39.00 ms    6.7%	0 s	 	    backing_store_DrawImage.llvm.7187528833409788268
39.00 ms    6.7%	0 s	 	     backing_store_delegate
37.00 ms    6.3%	0 s	 	      __backing_store_DrawImage_block_invoke
37.00 ms    6.3%	0 s	 	       ripc_DrawImage
35.00 ms    6.0%	0 s	 	        ripc_AcquireRIPImageData
35.00 ms    6.0%	0 s	 	         RIPImageCacheGetRetained
28.00 ms    4.8%	0 s	 	          RIPImageDataInitializeShared
28.00 ms    4.8%	0 s	 	           CGSImageDataLock
24.00 ms    4.1%	1.00 ms	 	            img_data_lock
21.00 ms    3.6%	0 s	 	             img_raw_read
20.00 ms    3.4%	0 s	 	              get_chunks_direct
20.00 ms    3.4%	0 s	 	               CGDataProviderDirectGetBytesAtPositionInternal
19.00 ms    3.2%	0 s	 	                provider_for_destination_get_bytes_at_position_inner
14.00 ms    2.4%	0 s	 	                 CGDataProviderDirectGetBytesAtPositionInternal
13.00 ms    2.2%	13.00 ms	 	                  _platform_memmove$VARIANT$Haswell
1.00 ms    0.1%	0 s	 	                  CGDataProviderRetainBytePtr
5.00 ms    0.8%	1.00 ms	 	                 vImageConverterConvert
4.00 ms    0.6%	0 s	 	                  vImageConverter_convert_internal
1.00 ms    0.1%	0 s	 	                0x7fff2e057120
1.00 ms    0.1%	1.00 ms	 	              0x7fff2e056ba0
1.00 ms    0.1%	0 s	 	             _CFRelease
1.00 ms    0.1%	1.00 ms	 	             0x7fff2e054c61
3.00 ms    0.5%	0 s	 	            img_image
2.00 ms    0.3%	0 s	 	             CGDataProviderCreateForDestinationWithImage
1.00 ms    0.1%	1.00 ms	 	             0x7fff2e051670
1.00 ms    0.1%	1.00 ms	 	            0x7fff2e054b4f
7.00 ms    1.2%	0 s	 	          cache_set_and_retain
7.00 ms    1.2%	0 s	 	           _cache_enforce_limits
1.00 ms    0.1%	0 s	 	        ripc_GetRenderingState
1.00 ms    0.1%	0 s	 	        ripc_RenderImage
1.00 ms    0.1%	0 s	 	         RIPLayerBltImage
1.00 ms    0.1%	0 s	 	          ripl_Mark
1.00 ms    0.1%	0 s	 	           argb32_image
1.00 ms    0.1%	0 s	 	            argb32_image_mark_image
1.00 ms    0.1%	1.00 ms	 	             argb32_image_mark_argb32
1.00 ms    0.1%	0 s	 	      0x7fff2afb6c4b
1.00 ms    0.1%	0 s	 	      -[_NSCGSWindowBackingStore lockBackBuffer]
9.00 ms    1.5%	0 s	 	   CGBitmapContextCreateImage
8.00 ms    1.3%	0 s	 	    CGDataProviderCreateTrustedWithCopyOfData
8.00 ms    1.3%	0 s	 	     CGDataProviderCreateWithCopyOfData
1.00 ms    0.1%	0 s	 	    CGImageCreate
6.00 ms    1.0%	0 s	 	   _CFRelease
1.00 ms    0.1%	0 s	 	   0x7fff2e040e5e
```

And with Full Animation on:
```
3.10 s   82.7%	0 s	 	  -[OTTD_QuartzView drawRect:]
3.04 s   81.2%	0 s	 	   CGContextDrawImageWithOptions
3.04 s   81.2%	0 s	 	    backing_store_DrawImage.llvm.7187528833409788268
3.04 s   81.2%	0 s	 	     backing_store_delegate
3.04 s   81.1%	0 s	 	      __backing_store_DrawImage_block_invoke
3.04 s   81.1%	0 s	 	       ripc_DrawImage
1.84 s   49.1%	0 s	 	        ripc_RenderImage
1.84 s   49.1%	0 s	 	         RIPLayerBltImage
1.84 s   49.1%	0 s	 	          ripl_Mark
1.84 s   49.1%	0 s	 	           argb32_image
1.84 s   49.1%	0 s	 	            argb32_image_mark_image
1.84 s   49.0%	1.84 s	 	             argb32_image_mark_argb32
1.00 ms    0.0%	1.00 ms	 	             0x7fff2e0b00c0
1.00 ms    0.0%	1.00 ms	 	             madvise
1.00 ms    0.0%	1.00 ms	 	             0x7fff2e0affb8
1.00 ms    0.0%	1.00 ms	 	             0x7fff2e0b00c7
1.19 s   31.8%	0 s	 	        ripc_AcquireRIPImageData
1.19 s   31.8%	0 s	 	         RIPImageCacheGetRetained
1.10 s   29.3%	0 s	 	          RIPImageDataInitializeShared
1.10 s   29.3%	0 s	 	           CGSImageDataLock
1.10 s   29.3%	0 s	 	            img_data_lock
1.10 s   29.2%	0 s	 	             img_raw_read
1.09 s   29.2%	0 s	 	              get_chunks_direct
1.09 s   29.2%	0 s	 	               CGDataProviderDirectGetBytesAtPositionInternal
1.08 s   28.8%	8.00 ms	 	                provider_for_destination_get_bytes_at_position_inner
604.00 ms   16.1%	1.00 ms	 	                 vImageConverterConvert
598.00 ms   15.9%	0 s	 	                  vImageConverter_convert_internal
2.00 ms    0.0%	2.00 ms	 	                  0x7fff652aadfc
1.00 ms    0.0%	1.00 ms	 	                  0x7fff2e02529b
1.00 ms    0.0%	1.00 ms	 	                  0x7fff652aae10
1.00 ms    0.0%	1.00 ms	 	                  0x7fff2e025b92
454.00 ms   12.1%	0 s	 	                 CGDataProviderDirectGetBytesAtPositionInternal
434.00 ms   11.5%	434.00 ms	 	                  _platform_memmove$VARIANT$Haswell
8.00 ms    0.2%	0 s	 	                  CGDataProviderRetainBytePtr
5.00 ms    0.1%	0 s	 	                  CGDataProviderReleaseBytePtr
1.00 ms    0.0%	1.00 ms	 	                  pthread_mutex_lock
1.00 ms    0.0%	1.00 ms	 	                  0x7fff2e0262e6
1.00 ms    0.0%	1.00 ms	 	                  0x7fff2dcd40e6
1.00 ms    0.0%	1.00 ms	 	                  0x7fff652aaeb0
1.00 ms    0.0%	0 s	 	                  _CFRelease
1.00 ms    0.0%	1.00 ms	 	                  0x7fff652b4637
1.00 ms    0.0%	1.00 ms	 	                  0x7fff2e0260aa
3.00 ms    0.0%	3.00 ms	 	                 _platform_memmove$VARIANT$Haswell
1.00 ms    0.0%	1.00 ms	 	                 0x7fff2e056c35
1.00 ms    0.0%	1.00 ms	 	                 0x7fff2e056c51
1.00 ms    0.0%	1.00 ms	 	                 0x7fff2e025a0a
1.00 ms    0.0%	1.00 ms	 	                 0x7fff2e0259cc
1.00 ms    0.0%	1.00 ms	 	                 0x7fff2e025980
1.00 ms    0.0%	1.00 ms	 	                 0x7fff652aae85
1.00 ms    0.0%	1.00 ms	 	                 0x7fff2e025a27
1.00 ms    0.0%	1.00 ms	 	                 0x7fff2e056c2b
1.00 ms    0.0%	0 s	 	                 0x7fff2e0259bc
1.00 ms    0.0%	1.00 ms	 	                 0x7fff2e37e83a
1.00 ms    0.0%	0 s	 	                 0x7fff2e0259e6
1.00 ms    0.0%	1.00 ms	 	                 0x7fff2e025b5b
1.00 ms    0.0%	0 s	 	                0x7fff2e056ed8
1.00 ms    0.0%	1.00 ms	 	                0x7fff2e056e2f
1.00 ms    0.0%	1.00 ms	 	                0x7fff2e057033
1.00 ms    0.0%	1.00 ms	 	                CGDataProviderReleaseBytePtr
1.00 ms    0.0%	1.00 ms	 	                0x7fff2e057737
1.00 ms    0.0%	1.00 ms	 	                0x7fff2e056e43
1.00 ms    0.0%	1.00 ms	 	                0x7fff2e0570a3
1.00 ms    0.0%	1.00 ms	 	                _platform_memmove$VARIANT$Haswell
1.00 ms    0.0%	1.00 ms	 	                0x7fff2e057070
1.00 ms    0.0%	1.00 ms	 	                CGBitmapPixelInfoGetBitsPerPixel
1.00 ms    0.0%	1.00 ms	 	                0x7fff2e0263e2
1.00 ms    0.0%	1.00 ms	 	                0x7fff2e056f7f
1.00 ms    0.0%	1.00 ms	 	                0x7fff2e056e61
1.00 ms    0.0%	1.00 ms	 	               0x7fff2e056d93
1.00 ms    0.0%	1.00 ms	 	              0x7fff2e056ba4
1.00 ms    0.0%	0 s	 	             _CFRelease
1.00 ms    0.0%	0 s	 	             CGSImageDataHandleCreate
1.00 ms    0.0%	0 s	 	              malloc_zone_calloc
1.00 ms    0.0%	0 s	 	            img_image
1.00 ms    0.0%	0 s	 	             CGDataProviderCreateForDestinationWithImage
95.00 ms    2.5%	0 s	 	          cache_set_and_retain
95.00 ms    2.5%	0 s	 	           _cache_enforce_limits
2.00 ms    0.0%	0 s	 	        ripc_GetRenderingState
1.00 ms    0.0%	0 s	 	        RIPImageCacheRelease
1.00 ms    0.0%	0 s	 	       0x7fff2e04c687
1.00 ms    0.0%	0 s	 	      -[_NSCGSWindowBackingStore dirtyBackBufferInRegion:]
1.00 ms    0.0%	0 s	 	    0x7fff2b2aa546
45.00 ms    1.2%	0 s	 	   _CFRelease
11.00 ms    0.2%	0 s	 	   CGBitmapContextCreateImage
11.00 ms    0.2%	0 s	 	    CGDataProviderCreateTrustedWithCopyOfData
11.00 ms    0.2%	0 s	 	     CGDataProviderCreateWithCopyOfData
1.00 ms    0.0%	1.00 ms	 	   0x7fff2e04bd68
```

As you can see, when enabled, the routine takes up ~80% of CPU time vs ~9% when off.


[Raw instruments trace (in xcode format)](https://github.com/OpenTTD/OpenTTD/files/3831329/OpenTTD.Nightly.2019-11-03.Full.Anim.Of.vs.On.trace.zip)

**Comment by Eddi-z** [comment]
Well, it is somewhat expected that palette animation is slow, because almost no hardware supports the kind of palette animation anymore, that the game was built on. on modern hardware, you'd expect this to be done in a GPU shader, but to my knowledge, noone has actually implemented this

however, that's not a reason why it should be this bad.

**Comment by Honza1987** [comment]
I tried with beta, it is better but when I try the same with 1.8.0. It works more than proper!!

**Comment by msikma** [comment]
Really glad people are still working on this.

I've had to stay on 1.8.0 as well because I'm getting exactly the same problem. Both 1.9.3 and 1.10.0-beta2 have the same issue. It's a little bit better when turning off "full animation", which at least makes the cursor move at full speed again and speeds up the game a little, but scrolling performance is still really bad. So even just turning that off is not a real workaround. It's a world of difference with 1.8.0 which is perfectly smooth.

edit: I should mention, when I run the Windows version of OpenTTD 1.9.3 in my Windows 7 VM (using VMware Fusion), it runs super fast as it should.

**Comment by Honza1987** [comment]
Hi,

yup point is why it works properly on 1.8.0 and it does not at higher

**Comment by anderium** [comment]
Running an almost fresh version of OpenTTD 1.9.3 on macOS 10.14.6 with internal retina display.
Trees are set to transparent.

* Playing on a new 64&times;64 map gives a simulation rate of 14-18 fps with Full animation turned on.
    * FFWD runs the game with 40 to 80 fps, however, moving the mouse seems to double this easily. Moving the cursor quick or at a normal speed seems to have almost no difference. 
* Playing on that same 64&times;64 map with Full animation turned off gives a simulation rate of 33.33 as expected.
    * FFWD runs the game at 5,000 to 9,000 simulation frames per second and 230 to 250 frames for the graphics. 
* Playing on a new 4096&times;4096 map does not change the simulation rate of 14-18 fps with Full animation turned on.
    * FFWD runs the game with only 20 to 30 fps, however, moving the mouse now seems to make no change.
* Playing, again, on that same 4096&times;4096 map with Full animation turned off still gives a simulation rate of 33.33 as expected.
    * FFWD runs the game at 100 to 130 simulation frames per second, drawing frames follow.

      (Zooming out on the 4096 map makes the game run slower, which makes sense right?)

This really does mean that there must be something with full animation that makes the time to render incredibly high. 

--------

Also, here's something that's probably not related, but also happened: When installing I got an error that there were no music files available (it was the first time I download OpenTTD on this device)

**Comment by nielsmh** [comment]
Some instrumented testing reveals that this call to get queued events occasionally takes very long to complete:
https://github.com/OpenTTD/OpenTTD/blob/ac7cc18ab9f5a06ac0261a69dc96a28e3f1136af/src/video/cocoa/event.mm#L406-L408

When running on a low-dpi display (15" 1680x1050) it almost always completes in less than 5 ms, but when running on a high-dpi display (23" 4k, with resolution scaling or not) it much more often takes a long time to return, often more than 20 or 30 ms. This delays everything and might explain some slowness.
I'm not sure if there is any solution other than wrapping the entire event loop in a thread that won't disturb the game loop timing as much.

**Comment by glx22** [comment]
> This really does mean that there must be something with full animation that makes the time to render incredibly high.

Yes it's because animation is done via palette animation, and we have to do it in software as modern graphic cards don't do it natively anymore (old 8bpp trick).

**Comment by nielsmh** [comment]
The above slowness of `nextEventMatchingMask:untilDate:inMode:dequeue:` is also described in this post on SO: https://stackoverflow.com/q/53490335
It seems to be a general problem experienced on macOS, not specific to OpenTTD. However OpenTTD's synchronous nature might be amplifying the effect of it.

I tested with the SDL2 video driver on the same system, and that does not have the same slowness issues, it runs at full 33-34 fps also on my 4k display.

**Comment by mackensen** [comment]
Agreed; performance is better if you compile with SDL and without Cocoa support (`--with-sdl --without-cocoa`).

**Comment by msikma** [comment]
> Yes it's because animation is done via palette animation, and we have to do it in software as modern graphic cards don't do it natively anymore (old 8bpp trick).

Surely it was done this way in 1.8.0 as well, though?

**Comment by Shortoz** [comment]
After reading some of the comments here, I think I may have come across a workaround that might help people who are having this issue. If you go to "System Preferences > Displays > Color" and change the Display Profile to "sRGB IEC61966-2.1" (as shown in the screenshot), the game's framerate should go up to normal.

<img width="780" alt="Screen Shot 2020-02-06 at 6 03 39 PM" src="https://user-images.githubusercontent.com/46329374/73986343-61a6a300-490b-11ea-98a3-da7d44f8cae2.png">

While using this profile, I'm able to get about 33 fps while moving the camera while the game is in fullscreen. Using the default "Color LCD" profile, my framerate drops to about 12 fps while moving the camera in fullscreen, making the game unplayable. Of course, your mileage may vary and others may not have the same improvement I have.

**Comment by mackensen** [comment]
@Shortoz your workaround works for me. I recompiled with cocoa support and without sdl support. If I switch color profiles I can see immediate improvement. If I go back to Color LCD performance degrades immediately.

**Comment by SoothedTau** [comment]
From what I can tell, OpenTTD has lost direct-to-display and the macOS compositor is kicking in to fix up things by converting all pixels to a different colorspace which is taking a lot of time.

OpenTTD should output in sRGB format which then should mean the compositor doesn't get in the way regardless of whether the display is P3 or sRGB.

I'm not sure what it currently outputs, but it's worth checking out. I don't currently have the time to do it myself though.

Some info can be found in this talk at 39:45 [here](https://developer.apple.com/videos/play/wwdc2017/601/) though it mostly talks about Metal the rules aren't much different for other content.

**Comment by msikma** [comment]
Confirm that this workaround brings my 1.9.3 back to identical performance as 1.8.0 even with 'full animations' enabled. Really nice find! I guess that explains where the problem is.

**Comment by SoothedTau** [comment]
The previous fix for this issue ([here](https://github.com/OpenTTD/OpenTTD/commit/994664dec590b7b8f406d3c2ecc153e77630b1db)) didn't actually solve the issue for all users. It would be best to force the use of sRGB color space on the window with something like this:
`[this->window setColorSpace:[NSColorSpace sRGBColorSpace]];`

As explained in the video: using sRGB color-space for the window should always result in direct to display and I can see much better performance forcing the window color space to sRGB on my MacBook Pro running latest Catalina. I measured performance using a tool and saw 3x improved performance; from ~110ms per frame to ~30ms (VSync limits this to ~33ms).

Forcing this causes the game to look different because the CG color space will get its color space from the window which is now sRGB and I think it used to expect RGB. There was debate before about what looks correct, I think the colors look oversaturated as it is currently and this is fixed once using sRGB but I'll leave it up to you. Regardless, sRGB should be the color space, if the colors come out 'wrong' it is the input colors that need to change, not the color space. Likely there is a misinterpretation of color-space earlier in the pipeline.

Anyway, that's the cause of the slowdown; color conversion by the OS because you lost direct-to-display due to color-space mismatch. Can be fixed by setting colorspace to sRGB on the window (or indeed workaround by changing display color).

Can't speak for all OS versions/machines/displays but that's whats happening on mine and what fixes it on my machine.

**Comment by michicc** [comment]
@SoothedTau Can you make a patch/PR for this so other people can test it easier?

**Comment by andythenorth** [comment]
I would find it really helpful to have a baseline test or tests.  This has become a giant thread of (useful) reports, but they might be about different things in different contexts.  The risk is chasing our tail fixing things with no measure of whether they're improved.

Are there standard savegames we can use?

**Comment by spauka** [comment]
@SoothedTau @michicc I implemented the solution you suggested, it would be great if someone could take a look?

**Comment by msikma** [comment]
> @SoothedTau @michicc I implemented the solution you suggested, it would be great if someone could take a look?

I just had a look. Unfortunately, it doesn't seem to have resolved the issue for me. Still a significant performance issue that goes away when switching the monitor over to an sRGB profile.

I built from the latest `cocoa_set_colorspace`. Here's my compiled bundle in case anyone wants to give it a try:

[OpenTTD-20200227-cocoa_set_colorspace-gda504c127d.zip](https://github.com/OpenTTD/OpenTTD/files/4262946/OpenTTD-20200227-cocoa_set_colorspace-gda504c127d.zip)

**Comment by spauka** [comment]
Interesting! I tried your build on Catalina (10.15.3), and didn't see performance issues (one core hovers at ~40% cpu). I've attached my build which works well for me if you want to try?

[openttd-custom-20200227-cocoa_set_colorspace-gda504c127d-OSX.zip](https://github.com/OpenTTD/OpenTTD/files/4264552/openttd-custom-20200227-cocoa_set_colorspace-gda504c127d-OSX.zip)

**Comment by msikma** [comment]
Thanks, I'll try your build tomorrow. Weird that it works for you. Do you not get any performance difference based on setting the monitor profile? edit: just in case, I'm on 10.14.6, and I'll provide some more info tomorrow.

**Comment by SoothedTau** [comment]
@msikma If you don't mind me asking; what OS build are you on and what hardware setup? I may try to repro.

Edit: Ah, Mojave. Hardware setup would be useful though!

Edit2: Performance is a lot better, but still not as it should be. I'll investigate further when I have time.

**Comment by msikma** [comment]
@SoothedTau Apologies for late response, here's my hardware setup:

* CPU: Intel Core i7-8086K Coffee Lake - 4.0 GHz (OC to 4.7 GHz)
* GPU: Sapphire NITRO+ Radeon RX Vega 56 8G
* Mem: Crucial Ballistix Sport LT 32GB Kit (16GBx2) DDR4
* SSD: Samsung 960 Pro 1TB SSD
* Motherboard: Asus ROG Strix Z370-G Gaming (Wi-Fi AC)
* Case: Corsair Carbide Air 240 Zwart
* Cooling: Corsair Hydro H105
* PSU: Corsair RM850i

As you can probably guess it's not an official Apple setup, so I think it's going to be difficult to compare actual benchmarks, but I can provide those. I am running OSX Mojave 10.14.6, and almost all of it is vanilla Apple software aside from a few things during startup.

I've got a triple monitor setup, and I didn't realize this before but that might make a difference too. I'll give it a try with only one connected later. All three of my monitors have separate color profiles and none of them are sRGB. 

Re: @spauka, sorry but I couldn't run your build since it requires OSX Catalina. The dreaded compatibility changes are forcing me to stay on Mojave unfortunately.

**Comment by SoothedTau** [comment]
> @SoothedTau Apologies for late response, here's my hardware setup:
> 
> * CPU: Intel Core i7-8086K Coffee Lake - 4.0 GHz (OC to 4.7 GHz)
> * GPU: Sapphire NITRO+ Radeon RX Vega 56 8G
> * Mem: Crucial Ballistix Sport LT 32GB Kit (16GBx2) DDR4
> * SSD: Samsung 960 Pro 1TB SSD
> * Motherboard: Asus ROG Strix Z370-G Gaming (Wi-Fi AC)
> * Case: Corsair Carbide Air 240 Zwart
> * Cooling: Corsair Hydro H105
> * PSU: Corsair RM850i
> 
> As you can probably guess it's not an official Apple setup, so I think it's going to be difficult to compare actual benchmarks, but I can provide those. I am running OSX Mojave 10.14.6, and almost all of it is vanilla Apple software aside from a few things during startup.
> 
> I've got a triple monitor setup, and I didn't realize this before but that might make a difference too. I'll give it a try with only one connected later. All three of my monitors have separate color profiles and none of them are sRGB.
> 
> Re: @spauka, sorry but I couldn't run your build since it requires OSX Catalina. The dreaded compatibility changes are forcing me to stay on Mojave unfortunately.

Ah right, don't have such a system lying around! 

Found what is causing the slowdown though:

- As fixed in the build @spauka made: color space should be sRGB. If it isn't you're likely to incur costly color space conversion when calling drawRect.
- Due to HiDPI, the real resolution of the backbuffer (CGContext texture) is actually twice the size of what OpenTTD thinks it is. See [this documentation on Supporting High Resolution](https://developer.apple.com/library/archive/documentation/GraphicsAnimation/Conceptual/HighResolutionOSX/APIs/APIs.html). Because the size of the CGContext doesn't match the view's CGContext size a scaling routine is applied when drawRect is called, again this takes quite some time.

You can prevent using drawRect entirely by using CGBitmapContextGetData on the view's context and memcpy'ing or otherwise copying the data in directly. With the format set to sRGB you shouldn't need any conversion, though you may want to implement 2x scaling to account for HiDPI when it is indeed present. 

When this is done, drawRect isn't necessary anymore and the only time spent is OpenTTD drawing and the upscale if HiDPI is enabled. You now have full control over how to implement the copies and you should be able to improve the performance should the need arise. All the copying now takes significant time so you may want to see what can be done.

**Comment by msikma** [comment]
I see this issue just got closed, but I don't understand why. I tested this fix and it didn't work for me. The last commit that got added is identical to the one I tested. Has anyone else tested it?

**Comment by andythenorth** [comment]
I commented on the pull request here https://github.com/OpenTTD/OpenTTD/pull/8023#issuecomment-605839221

TL;DR. For me: 
* frame rate is now higher
* graphics look worse

**Comment by msikma** [comment]
That's weird, because the patch definitely did not bring back 1.8.0 performance for me, to the point where I could tell with the naked eye easily. Did anybody else test it? And did they get the same performance as 1.8.0 or simply "better" performance without being too specific? I'm sorry if I sound a bit disappointed. I can log the difference in FPS to get hard numbers for this.

The difference in colors in the screenshot is an example of colors being interpreted as the wrong profile. The screenshot has "Display P3" as the embedded profile which is the user's system profile. Here's what happens when I take the left half of the image into Photoshop, convert it to sRGB, and then assign it the Display P3 profile without converting the color values:

![display-p3-2](https://user-images.githubusercontent.com/1507745/78079669-dbf42080-73ac-11ea-8d27-e419727e64bb.png)

They look identical again (minus some loss from the conversion roundtrip). The color differences could be greater or smaller than that of the user who posted the original image, depending on what color profile they use.

**Comment by spauka** [comment]
FWIW I think it might be worth reopening this issue, or opening a new issue regarding the colorspace issue and continuing performance problems on OSX.

The patch above makes the game playable but it does seem to fix all the issues that have been raised...

**Comment by nielsmh** [comment]
I think it would be a better use of time to work on an OpenGL based renderer which would most likely avoid all these issues.

**Comment by andythenorth** [comment]
I am happy in principle to have this or another issue open.

It would be helpful though to have quantified the issues.  It's unclear whether there is one mac performance issue or several. 

Apple is pretty much the only vendor where we can rely on there being 2 OS versions and only a handful of hardware versions :) 

It should be possible to categorise and reproduce the issues more reliably. :)  Currently we lack consistency, e.g. a common set of FPS numbers on a common set of savegames (or something like that).

**Comment by nielsmh** [comment]
Ideas for what might be a useful test:
- It needs to be repeatable.
- It needs to generate clear diagnostics and results.
- Testers need to accurately report hardware version, software versions, and display configuration the game is running on.
- Need to use a known config file for the game so settings like resolution, blitter, news messages, and full animation don't affect different testers' results differently.
- Probably involves running the game with the dummy video driver on a known savegame, for some number of ticks, to get the hardware's simulation rate capability when no graphics is involved. Then compare loading the same savegame in graphical mode and look at performance numbers.

**Comment by SoothedTau** [comment]
> I think it would be a better use of time to work on an OpenGL based renderer which would most likely avoid all these issues.

OpenGL is deprecated on macOS. I wouldn't recommend developing new features with it.

**Comment by msikma** [comment]
> It would be helpful though to have quantified the issues. It's unclear whether there is one mac performance issue or several.

You're absolutely right.

I'm sorry to say I tried to get some numbers on this but I haven't quite gotten them yet, because I tried to compile 1.8.0 to have a baseline and somehow that one doesn't run well on my system either (the official release does). It ran basically like the 1.9.0 release. So I'm not sure what's going on. I need to investigate this further.

I'd love to help out in some way so I'll be looking into this when I've got some more time. 🙂

**Comment by michicc** [comment]
Well, the official 1.8.0 release was build using a very old cross-compiler using and targeting the 10.6 (or maybe even 10.5) SDK. The current builds are done with a real native compiler on Azure infrastructure, using a SDK 10.10+ (not sure which exact versions Azure provides).

It it entirely possible that macOS exhibits different app compatibility changes depending on the OS version the app was compiled against.

**Comment by msikma** [comment]
Yeah, that's what I was thinking too. Could it be that this bug is really a result of SDK changes?

I'll look into compiling with an older SDK to see what happens.
